### ISSUE TITLE
Checkboxes should work like the Product Code Registry

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/obtv#17]
On the Product Code Registry clearing all checkboxes is equitable to checking all checkboxes (in both cases all data is returned).  The checkboxes also start off in a cleared space.  This appears to be how other major websites operate although further research could be performed.  In any case both web applications should work in an identical fashion (most likely the updates will be applied to OBTV although more research is warranted).

**Comment by shelcrow** [comment]
Addressed in #22
