### ISSUE TITLE
Concepts page speed issues

### ISSUE THREAD

**Issue by joelebwf** [SunSpecOrangeButton/obtv#7]
Concepts is currently slow loading and the Search Filters are too slow to actually use.  One of three methods is needed to improve speed:

1 - Best) VUE or another library for rendering improvements to the table control 
2 - Ok) Add filters so less data is returned (i.e. Only display one entrypoint at a time)
3 - Least Desirable) Use pagination to return less data

This issue involves researching all three approaches and selecting the most desirable item.

Please note that speed testing has been performed on Firefox to date - other browsers should be tested as well.

**Comment by shelcrow** [comment]
Resolved in commit #21
